name: directory_writer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - name: Write DIRECTORY.md
        run: |
          chmod +x scripts/build_directory_md.py
          scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Update DIRECTORY.md
        run: |
          git add DIRECTORY.md
          git commit -am "update DIRECTORY.md" ||  true
          git push --force origin HEAD:$GITHUB_REF || true